spring.application.name=InfoBaza
server.port=4921
server.address=0.0.0.0

# info
spring.datasource.info.url=jdbc:clickhouse://192.168.122.45:8123/gbd_fl0205?socket_timeout=300000&connect_timeout=60000&compress=0
spring.datasource.info.username=activestest
spring.datasource.info.password=active123
spring.datasource.info.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver

# itap
spring.datasource.main.url=jdbc:postgresql://192.168.122.121:5432/amigo
spring.datasource.main.username=postgres
spring.datasource.main.password=40593319
spring.datasource.main.driver-class-name=org.postgresql.Driver
spring.jpa.main.hibernate.ddl-auto=none
spring.jpa.main.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.main.show-sql=false

# ser
spring.datasource.ser.url=jdbc:postgresql://localhost:5433/kfm_new
spring.datasource.ser.username=sso_itap
spring.datasource.ser.password=L9LgcfKf#rD{
spring.datasource.ser.driver-class-name=org.postgresql.Driver
spring.jpa.ser.hibernate.ddl-auto=none
spring.jpa.ser.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.ser.show-sql=false

# dossier
spring.datasource.dossier.url=jdbc:postgresql://192.168.122.47:5432/amigo
spring.datasource.dossier.username=dossier_base
spring.datasource.dossier.password=40593319
spring.datasource.dossier.driver-class-name=org.postgresql.Driver
spring.jpa.dossier.hibernate.ddl-auto=none
spring.jpa.dossier.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.dossier.show-sql=false

jwt.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvPVlkg6rPbFPmPhPlO+uyiLnnIvz/3SNGuL6x01zac7Z9A6DuJubWigbc7wQhFROoWTbdDHpew1OQTLIg4Z6JbTCwpZBfWzLBsmK3aoIIqlc6Nkv5Qeob79YiY+VWKBHzpnOEPHDS2LA/KBZEdeY57xmpdRLyzFBsYkS0Dy5w1JVzE7OcAy1Y35mngkb1+ekaW4LBeuds1UvzrNaypA33DsE82fuJuGEwSS33/ePvlf2YtijhDIfUrve2LMGf0LHb50ZKW48TVQeS+vmIrL3ydyPlaXQN+kfbBvk//0A/0Ls8IW0uj1XLweXfy7jyZ92d3sc20B/8mo02Uf72qxBwwIDAQAB
hibernate.id.new_generator_mappings=true

dossier.jwtSecret=czj^b*f=)a#skb-!95*h8flo2n^ptjzbv!n42#b%q5yn68sq+8
dossier.jwtExpirationMs=900000
dossier.admin=040205551504


spring.datasource.hikari.socket-timeout=60000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl