status = debug
appenders = console, file

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

appender.file.type = RollingFile
appender.file.name = FILE
appender.file.fileName = logs/active.log
appender.file.filePattern = logs/%d{yyyy-MM}/%d{yyyy-MM-dd}.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
appender.file.policies.type = Policies
appender.file.policies.time.type = TimeBasedTriggeringPolicy
appender.file.policies.time.interval = 1
appender.file.policies.time.modulate = true
appender.file.policies.time.evaluateOnStartup = true
appender.file.policies.time.monitorInterval = 30
appender.file.strategy.type = DefaultRolloverStrategy
appender.file.strategy.delete.type = Delete
appender.file.strategy.delete.basePath = logs/
appender.file.strategy.delete.maxDepth = 2
appender.file.strategy.delete.ifLastModified.type = IfLastModified
appender.file.strategy.delete.ifLastModified.age = 180d
appender.file.immediateFlush = true

loggers = file
logger.file.name = org.info.infobaza.util.logging.LogService
logger.file.level = info
logger.file.appenderRefs = file
logger.file.appenderRef.file.ref = FILE
logger.file.additivity = false

rootLogger.level = info
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = CONSOLE